### ISSUE TITLE
You've got Zombies

### ISSUE THREAD

**Issue by rdebath** [Caerostris/gitfuck#1]
I'm not sure exactly what's wrong, but when I tried your interpreter/compiler on this BF program:

https://github.com/rdebath/Brainfuck/blob/master/bitwidth.b

I got this result.

``` log
$ ./a.out
Hello Zombie World! 255
$ 
```

The expected result is this:

``` log
$ ./a.out
Hello World! 255
$ 
```

PS: I like your implementation of the tape.

**Comment by Caerostris** [comment]
Thanks for this, @rdebath!
So it's definitely this check:
https://github.com/rdebath/Brainfuck/blob/master/bitwidth.b#L93
I'm still trying to figure out what exactly that Zombie check is doing. Brainfuck is currently doing it's thing here :P If I get your code right, you check that the compiler has 16 bit cells in L71, and then check if the compiler has 8 bit cells within the 16-bit-checked block. Right?

**Comment by rdebath** [comment]
Exactly. It's supposed to be checking for compilers that do a lot of optimising, but make the mistake of doing their constant folding (precalculation) with the wrong cell size. So, for example, the C code does it's calculation with integers, but the the generated code is using chars.

Because of this mixup in the cells sizes the dead code gets resurrected ... dead code running ... Zombie.

However, your compiler looks like it's a plain translation, one instruction at a time, from BF to assembler. So this particular diagnosis cannot apply.

**Comment by Caerostris** [comment]
I see. Yup, it's as plain as it can get. In fact, it's so plain that compiling 99 bottles of beer (~8K brainfuck) produces 128K assembler output. So something must be seriously wrong here.

**Comment by Caerostris** [comment]
Thanks for the PR, would've taken me ages to find that stupid bug!
